import NavierStokes.ResidualCalculus
import NavierStokes.MixedDiagonalResidual
import NavierStokes.V513ScaleRetainingCutProducts

/-!
# v5.15: exact strict-vs-doubling residual difference

The paired construction changes only the diagonal cutoff schedule.  Before
taking norms, this module records the exact PDE-level perturbation generated by
that change.

For two schedules `aStrict` and `aDouble`, define

  δu = uDouble - uStrict,
  δp = pDouble - pStrict.

On every interior time slice where the two assembled fields are smooth, the
difference of their literal Navier--Stokes residuals is exactly the six-term
perturbation identity already certified by `ResidualCalculus`:

  ∂t δu - Δ δu + ∇ δp
    + D uStrict[δu] + D δu[uStrict] + D δu[δu].

No norm ordering is asserted.  This is the algebraic bridge needed before the
scale-retaining cutoff-product estimates can be applied term by term.
-/

noncomputable section

namespace NavierStokes.V515ExactResidualDifference

open ProblemStatement Set
open scoped Topology ContDiff

/-- Velocity difference induced by changing only the diagonal schedule. -/
def deltaVelocity
    (aStrict aDouble : ℕ → ℝ) (q : SpaceTime → ℝ)
    (A B : ℕ → VelocityField) : VelocityField :=
  fun z =>
    MixedDiagonalResidual.velocity aDouble q A B z -
      MixedDiagonalResidual.velocity aStrict q A B z

/-- Pressure difference induced by changing only the diagonal schedule. -/
def deltaPressure
    (aStrict aDouble : ℕ → ℝ) (q : SpaceTime → ℝ)
    (P : ℕ → PressureField) : PressureField :=
  fun z =>
    MixedDiagonalResidual.pressure aDouble q P z -
      MixedDiagonalResidual.pressure aStrict q P z

/-- The assembled double-schedule fields are the strict-schedule fields plus
their schedule-induced differences. -/
theorem assembled_eq_strict_add_delta
    (aStrict aDouble : ℕ → ℝ) (q : SpaceTime → ℝ)
    (A B : ℕ → VelocityField) (P : ℕ → PressureField) :
    (fun z =>
      MixedDiagonalResidual.velocity aStrict q A B z +
        deltaVelocity aStrict aDouble q A B z) =
        MixedDiagonalResidual.velocity aDouble q A B ∧
    (fun z =>
      MixedDiagonalResidual.pressure aStrict q P z +
        deltaPressure aStrict aDouble q P z) =
        MixedDiagonalResidual.pressure aDouble q P := by
  constructor
  · funext z
    simp only [deltaVelocity]
    abel
  · funext z
    simp only [deltaPressure]
    abel

/-- Exact six-term perturbation formula for the literal mixed residuals of two
schedule choices.  Every field in the identity is the pinned construction's
actual assembled field; no proxy residual is introduced. -/
theorem residual_difference_exact
    (aStrict aDouble : ℕ → ℝ) (q : SpaceTime → ℝ)
    (A B : ℕ → VelocityField) (P : ℕ → PressureField)
    (hUStrict : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.velocity aStrict q A B) preSingularDomain)
    (hUDouble : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.velocity aDouble q A B) preSingularDomain)
    (hPStrict : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.pressure aStrict q P) preSingularDomain)
    (hPDouble : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.pressure aDouble q P) preSingularDomain)
    (t : ℝ) (ht : t ∈ Ioo (0 : ℝ) 1) (x : Space) :
    MixedDiagonalResidual.residual aDouble q A B P (t, x) -
        MixedDiagonalResidual.residual aStrict q A B P (t, x) =
      temporalDerivative (deltaVelocity aStrict aDouble q A B) t x -
        spatialLaplacian (deltaVelocity aStrict aDouble q A B) t x +
        pressureGradient (deltaPressure aStrict aDouble q P) t x +
        spatialDerivative (MixedDiagonalResidual.velocity aStrict q A B) t x
          (deltaVelocity aStrict aDouble q A B (t, x)) +
        spatialDerivative (deltaVelocity aStrict aDouble q A B) t x
          (MixedDiagonalResidual.velocity aStrict q A B (t, x)) +
        spatialDerivative (deltaVelocity aStrict aDouble q A B) t x
          (deltaVelocity aStrict aDouble q A B (t, x)) := by
  have hDeltaU :
      ContDiffOn ℝ ∞ (deltaVelocity aStrict aDouble q A B) preSingularDomain := by
    change ContDiffOn ℝ ∞
      (fun z =>
        MixedDiagonalResidual.velocity aDouble q A B z -
          MixedDiagonalResidual.velocity aStrict q A B z)
      preSingularDomain
    exact hUDouble.sub hUStrict
  have hDeltaP :
      ContDiffOn ℝ ∞ (deltaPressure aStrict aDouble q P) preSingularDomain := by
    change ContDiffOn ℝ ∞
      (fun z =>
        MixedDiagonalResidual.pressure aDouble q P z -
          MixedDiagonalResidual.pressure aStrict q P z)
      preSingularDomain
    exact hPDouble.sub hPStrict
  have h :=
    ResidualCalculus.navierStokesResidual_add_sub_of_smooth
      (MixedDiagonalResidual.velocity aStrict q A B)
      (deltaVelocity aStrict aDouble q A B)
      (MixedDiagonalResidual.pressure aStrict q P)
      (deltaPressure aStrict aDouble q P)
      hUStrict hDeltaU hPStrict hDeltaP t ht x
  obtain ⟨hu, hp⟩ :=
    assembled_eq_strict_add_delta aStrict aDouble q A B P
  rw [hu, hp] at h
  simpa only [MixedDiagonalResidual.residual] using h

/-- Equivalent source-facing form: use the exact pinned
`MixedPeriodicAssembly.originalResidual` on both sides. -/
theorem originalResidual_difference_exact
    (aStrict aDouble : ℕ → ℝ) (q : SpaceTime → ℝ)
    (A B : ℕ → VelocityField) (P : ℕ → PressureField)
    (hUStrict : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.velocity aStrict q A B) preSingularDomain)
    (hUDouble : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.velocity aDouble q A B) preSingularDomain)
    (hPStrict : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.pressure aStrict q P) preSingularDomain)
    (hPDouble : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.pressure aDouble q P) preSingularDomain)
    (t : ℝ) (ht : t ∈ Ioo (0 : ℝ) 1) (x : Space) :
    MixedPeriodicAssembly.originalResidual
        (SolenoidalDiagonal.potentialSum aDouble q A)
        (SolenoidalDiagonal.potentialSum aDouble q B)
        (SolenoidalDiagonal.potentialSum aDouble q P) (t, x) -
      MixedPeriodicAssembly.originalResidual
        (SolenoidalDiagonal.potentialSum aStrict q A)
        (SolenoidalDiagonal.potentialSum aStrict q B)
        (SolenoidalDiagonal.potentialSum aStrict q P) (t, x) =
      temporalDerivative (deltaVelocity aStrict aDouble q A B) t x -
        spatialLaplacian (deltaVelocity aStrict aDouble q A B) t x +
        pressureGradient (deltaPressure aStrict aDouble q P) t x +
        spatialDerivative (MixedDiagonalResidual.velocity aStrict q A B) t x
          (deltaVelocity aStrict aDouble q A B (t, x)) +
        spatialDerivative (deltaVelocity aStrict aDouble q A B) t x
          (MixedDiagonalResidual.velocity aStrict q A B (t, x)) +
        spatialDerivative (deltaVelocity aStrict aDouble q A B) t x
          (deltaVelocity aStrict aDouble q A B (t, x)) := by
  simpa only [MixedDiagonalResidual.residual_eq_originalResidual] using
    residual_difference_exact aStrict aDouble q A B P
      hUStrict hUDouble hPStrict hPDouble t ht x

end NavierStokes.V515ExactResidualDifference
