import NavierStokes.ResidualStability
import NavierStokes.V515ExactResidualDifference

/-!
# v5.18: quantitative paired residual jet bound

v5.15 identifies the exact residual perturbation generated by changing only
the diagonal cutoff schedule.  The pinned source already proves a sharp
fixed-order nonlinear stability estimate for precisely this perturbation.

This module specializes that source theorem to the paired mixed fields.  If
the strict-schedule background jets are bounded by A, the schedule-induced
velocity-difference jets by W, and pressure-difference jets by P, then the
m-th residual-difference jet is bounded by

  ||timeJet|| W + ||laplaceJet|| W + ||pressureJet|| P
    + ||spaceRestriction|| 2^m A W
    + ||spaceRestriction|| 2^m W A
    + ||spaceRestriction|| 2^m W^2.

This is a quantitative bridge only.  No schedule ordering is inferred unless
one separately proves smaller paired difference jets.
-/

noncomputable section

namespace NavierStokes.V518PairedResidualJetBound

open ProblemStatement Set
open scoped Topology ContDiff

theorem paired_residual_difference_jet_bound
    (aStrict aOther : ℕ → ℝ) (q : SpaceTime → ℝ)
    (A B : ℕ → VelocityField) (P : ℕ → PressureField)
    (hUStrict : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.velocity aStrict q A B) preSingularDomain)
    (hUOther : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.velocity aOther q A B) preSingularDomain)
    (hPStrict : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.pressure aStrict q P) preSingularDomain)
    (hPOther : ContDiffOn ℝ ∞
      (MixedDiagonalResidual.pressure aOther q P) preSingularDomain)
    {z : SpaceTime} (hz : z ∈ preSingularDomain)
    (m : ℕ) {Abg Wdiff Pdiff : ℝ}
    (huBound : ∀ k : ℕ, k ≤ m + 1 →
      ‖iteratedFDeriv ℝ k
        (MixedDiagonalResidual.velocity aStrict q A B) z‖ ≤ Abg)
    (hduBound : ∀ k : ℕ, k ≤ m + 2 →
      ‖iteratedFDeriv ℝ k
        (V515ExactResidualDifference.deltaVelocity
          aStrict aOther q A B) z‖ ≤ Wdiff)
    (hdpBound : ∀ k : ℕ, k ≤ m + 1 →
      ‖iteratedFDeriv ℝ k
        (V515ExactResidualDifference.deltaPressure
          aStrict aOther q P) z‖ ≤ Pdiff) :
    ‖iteratedFDeriv ℝ m
      (fun y =>
        MixedDiagonalResidual.residual aOther q A B P y -
          MixedDiagonalResidual.residual aStrict q A B P y) z‖ ≤
      ‖ResidualStability.timeJet‖ * Wdiff +
        ‖ResidualStability.laplaceJet‖ * Wdiff +
        ‖ResidualStability.pressureJet‖ * Pdiff +
        ‖ResidualStability.spaceRestriction Space‖ * (2 : ℝ) ^ m *
          Abg * Wdiff +
        ‖ResidualStability.spaceRestriction Space‖ * (2 : ℝ) ^ m *
          Wdiff * Abg +
        ‖ResidualStability.spaceRestriction Space‖ * (2 : ℝ) ^ m *
          Wdiff * Wdiff := by
  let u := MixedDiagonalResidual.velocity aStrict q A B
  let w := V515ExactResidualDifference.deltaVelocity
    aStrict aOther q A B
  let p := MixedDiagonalResidual.pressure aStrict q P
  let r := V515ExactResidualDifference.deltaPressure
    aStrict aOther q P

  have hw : ContDiffOn ℝ ∞ w preSingularDomain := by
    change ContDiffOn ℝ ∞
      (fun y =>
        MixedDiagonalResidual.velocity aOther q A B y -
          MixedDiagonalResidual.velocity aStrict q A B y)
      preSingularDomain
    exact hUOther.sub hUStrict

  have hr : ContDiffOn ℝ ∞ r preSingularDomain := by
    change ContDiffOn ℝ ∞
      (fun y =>
        MixedDiagonalResidual.pressure aOther q P y -
          MixedDiagonalResidual.pressure aStrict q P y)
      preSingularDomain
    exact hPOther.sub hPStrict

  have hfields :=
    V515ExactResidualDifference.assembled_eq_strict_add_delta
      aStrict aOther q A B P

  have heq :
      (fun y =>
        MixedDiagonalResidual.residual aOther q A B P y -
          MixedDiagonalResidual.residual aStrict q A B P y) =
        ResidualStability.residualDifference u w p r := by
    funext y
    rcases hfields with ⟨huEq, hpEq⟩
    unfold ResidualStability.residualDifference
    rw [← huEq, ← hpEq]
    rfl

  rw [heq]
  exact ResidualStability.residualDifference_jet_bound
    isOpen_preSingularDomain
    hUStrict hw hPStrict hr hz m huBound hduBound hdpBound

end NavierStokes.V518PairedResidualJetBound
